title: nur docs
description: Documentation for nur - a taskrunner based on nu shell
theme: just-the-docs

url: https://nur-taskrunner.github.io/docs/

nav_external_links:
  - title: nur on GitHub
    url: https://github.com/ddanier/nur

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
